### PR TITLE
Phantomjs 2.1.1

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by lfryc** [comment]
I get following error when trying to execute tests locally:

````
/Users/lfryc/workspaces/arquillian/arquillian-phantom-driver/target/phantomjs/phantomjs: cannot execute binary file
````

when trying to execute that executable:

````
./target/phantomjs/phantomjs -v
zsh: exec format error: ./target/phantomjs/phantomjs
````

**Comment by lfryc** [comment]
I'ev tried a macosx binary intalled locally and it worked correctly.

I believe the stage package is somehow corrupted.

**Comment by MatousJobanek** [comment]
re-staged and tested - all tests passed https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/Arquillian/job/Arquillian-phantom-driver-mjobanek/53/
tested also manually

**Comment by MatousJobanek** [comment]
waiting till arquillian-phantom-binary is public, then will release arquillian-phantom-driver 1.2.0.Final

**Comment by lfryc** [comment]
Perfect, thanks @MatousJobanek !

**Comment by lfryc** [comment]
the dependencies are aligned with arquillian universe?

**Comment by lfryc** [comment]
Btw @MatousJobanek I've tried to build Drone and Graphene against this PR (1.2.0-SNAPSHOT) and tests are :green_heart: 

So: :+1:

**Comment by MatousJobanek** [comment]
Well, the tests are filing in my case - https://github.com/arquillian/arquillian-extension-drone/pull/58
the related build: https://travis-ci.org/arquillian/arquillian-extension-drone/builds/105149612
btw. 1.2.0.Final (this PR) is staged here: https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-7585
Nevertheless, I don't think that it is a phantomjs-driver problem, so I don't see it as a blocker for 1.2.0.Final release...

**Comment by MatousJobanek** [comment]
It's probably a bug there in the ghostdriver https://github.com/detro/ghostdriver/issues/365

**Comment by MatousJobanek** [comment]
merged and released - the problem is not in the driver - it is caused by the combination of the newest Selenium, newest PhantomJS and improper Drone testsuite

**Pull request merged**
